// User Actions
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_REMOVE = 'USER_REMOVE';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_ERROR = 'USER_ERROR';

export const LISTING_LOADING = 'LISTING_LOADING';
export const LISTING_LOADED = 'LISTING_LOADED';
export const LISTING_REMOVE = 'LISTING_REMOVE';
export const LISTING_UPDATED = 'LISTING_UPDATED';
export const LISTING_ERROR = 'LISTING_ERROR';

export const ADDRESS_ERROR = 'ADDRESS_ERROR';
export const ADDRESS_LOADED = 'ADDRESS_LOADED';
export const ADDRESS_LOADING = 'ADDRESS_LOADING';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';

export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_LOADED = 'PAYMENT_LOADED';
export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const PAYMENT_CREATED = 'PAYMENT_CREATED';
export const PAYMENT_UPDATED = 'PAYMENT_UPDATED';
export const PAYMENT_DELETED = 'PAYMENT_DELETED';

export const FAVORITES_LOADED = 'FAVORITES_LOADED';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_ERROR = 'FAVORITES_ERROR';
export const FAVORITE_ADD = 'FAVORITE_ADD';
export const FAVORITE_REMOVE = 'FAVORITE_REMOVE';